In [28]:
import numpy as np
import sympy

A = np.array([[3, 8], [4, 11]])
b = np.array([[5], [7]])

print(A)
print(b)

#T = np.array([[3, 8, 5], [4, 11, 7]])
T = np.hstack((A, b))
print(T)

R = sympy.Matrix(T).rref()[0]
R = np.array(R)

print(R)

[[ 3  8]
 [ 4 11]]
[[5]
 [7]]
[[ 3  8  5]
 [ 4 11  7]]
[[1 0 -1]
 [0 1 1]]


In [31]:
# Skriv ut elementet nederst til høyre
print(T[1][2])

7


In [33]:
print(A)

print(A.T)           # den transponerte

K = np.linalg.inv(A) # inversmatrise
print(K)
print(A@K)
print(K@A)

[[ 3  8]
 [ 4 11]]
[[ 3  4]
 [ 8 11]]
[[11. -8.]
 [-4.  3.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [34]:
print(np.linalg.det(A)) #determinanten

1.0


In [35]:
x = K@b

print(x)

[[-1.]
 [ 1.]]
